# general settings
name: CSINet_x4_B32_C56_l1e-3_g_Adan_(1,2,4,4)_V1
model_type: SRModel
scale: 4
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 100

# dataset and data loader settings
datasets:
  train:
    name: DIV2K
    type: PairedImageDataset
#    dataroot_gt: /mnt/yxsun/Project/Data/datasets/DIV2K/DIV2K_train_HR_sub
#    dataroot_lq: /mnt/yxsun/Project/Data/datasets/DIV2K/DIV2K_train_LR_bicubic/X4_sub
#    (for lmdb)
#    dataroot_gt: C:\Dataset\train\DIV2K_train_HR_sub
#    dataroot_lq: C:\Dataset\train\DIV2K_train_LR_bicubic_x4_sub
    dataroot_gt: C:\Dataset\train\DIV2K_train_HR_sub
    dataroot_lq: C:\Dataset\train\DIV2K_train_LR_bicubic_X4_sub
    filename_tmpl: '{}'
    io_backend:
      type: disk
      # (for lmdb)
      # type: lmdb

    gt_size: 192
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 32
    dataset_enlarge_ratio: 100
    prefetch_mode: cuda
    pin_memory: true



  val_1: # the 1st test dataset
    name: Set5
    type: PairedImageDataset
    dataroot_gt: C:\Dataset\test\Set5\HR
    dataroot_lq: C:\Dataset\test\Set5\LR_bicubic\X4
    filename_tmpl: '{}x4'
    io_backend:
      type: disk

  val_2: # the 2st test dataset
    name: Set14
    type: PairedImageDataset
    dataroot_gt: C:\Dataset\test\Set14\HR
    dataroot_lq: C:\Dataset\test\Set14\LR_bicubic\X4
    filename_tmpl: '{}x4'
    io_backend:
      type: disk

# network structures
ema_decay: 0.999
network_g:
  type: CSINet
  num_in_ch: 3
  num_feat: 56
  num_block: 4
  num_out_ch: 3
  upscale: 4

# path
path:
  pretrain_network_g: ~ #C:\code\BSRN-main\experiments\CSINets_C56_adam_ema_x4_fine_tune_10k\models\net_g_170000.pth   #C:\code\BSRN-main\experiments\CSINets_C56_adam_ema_x2_fine_tune_10kv2\models\net_g_5000.pth # #C:\code\BSRN-main\experiments\pretrained_models\CSINet_x2_95000.pth #D:\code\BSRN-main\experiments\CSINet_x2_B32_C56_l1e-3_g96_Adan_v2_ELKA\models\net_g_910000.pth
  strict_load_g: false
  resume_state: ~

# training settings
train:
#  ema_decay: 0.999
#  optim_g:
#    type: Adam
#    lr: !!float 1e-3
#    weight_decay: 0
#    betas: [0.9, 0.999]
##
#  scheduler:
#    type: CosineAnnealingRestartLR
#    periods: [1000000]
#    restart_weights: [1]
#    eta_min: !!float 1e-6
#
#
#  total_iter: 1000000
#  warmup_iter: -1  # no warm up
  ema_decay: 0.999
  optim_g:
    type: Adan
    lr: !!float 3e-3
    betas: [ 0.98, 0.92, 0.99 ]
    weight_decay: 0
    foreach: true


#    scheduler:
#      type: CosineAnnealingRestartLR
#      periods: [1000000]
#      restart_weights: [1]
#      eta_min: !!float 1e-7

  scheduler:
    type: MultiStepLR
    milestones: [600000,800000]
    gamma: 0.5
##
  total_iter: 1000000
  warmup_iter: -1  # no warm up



  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: 5000
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: true

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~
    entity: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
